### ISSUE TITLE
Crawl entirety of PyTorch docs 🛠️ 

### ISSUE THREAD

**Issue by Nolski** [OpenMined/threepio#7]
# Summary

Crawler is only crawling a subsection of PyTorch API endpoints.

# Bug Acceptance Criteria

## Context

The output of the crawler for `torch.json` is not as expected.

## Expected behavior

`torch.json` contains all PyTorch API endpoints when crawls are run.

## Actual behavior

`torch.json` only has around 60 api endpoints which is far below the actual amount of API endpoints.

**Screenshots & links**:

https://github.com/OpenMined/threepio/blob/package-init/docs-crawler/docs/output/torch.json

**Comment by AmrMKayid** [comment]
Hey Mike,
I think what causes the bug is that each torch API has a different URL!
the output for the `torch.json` file stores only the APIs for `torch` API webpage
https://github.com/OpenMined/threepio/blob/a29223629dd8881e2fc4e6db4715756dba41d33f/docs-crawler/docs/docs/spiders/torch_spider.py#L12-L14
